services:
#  mongo:
#    container_name: mongo-product-service
#    image: mongo:latest
#    ports:
#    - 27017:27017
#    volumes:
#    - D:\DataVolume\product-microservice\mongo:/data/db
  mysql:
    container_name: mysql-product-service
    image: mysql:latest
    ports:
    - 3306:3306
    volumes:
    - D:\DataVolume\product-microservice\mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
