server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://product
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/(?<remaining>.*), /api/v1/$\{remaining}
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/(?<remaining>.*), /api/v1//$\{remaining}
        - id: inventory-route
          uri: lb://inventory-service
          predicates:
            - Path=/inventories/**
          filters:
            - RewritePath=/(?<remaining>.*), /api/v1/$\{remaining}
        - id: eureka-server-route
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: eureka-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/microservice-realm
management:
  tracing:
    sampling:
      probability: 1.0


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.RouteDefinitionLocator: INFO
    org.springframework.security: DEBUG

